from llm_client import ask_gemini


class UIAgent:
    def run(self, task: str, content_data=None, pages=None, website_type="website", user_prompt=""):
        component_name = task.replace("Generate", "").strip()

        prompt = f"""
You are a professional frontend UI component generator.

Website Type:
{website_type}

User Request:
{user_prompt}

Component to Generate:
{component_name}

Website Pages:
{pages}

Content Data:
{content_data}

Generate ONLY the HTML for the component named: {component_name}

Strict rules:
- Return only HTML.
- Do not return markdown.
- Do not use ```html.
- Do not generate a full HTML document.
- Do not generate unrelated components.
- Do not generate navbar/header unless the component is Navbar.
- Do not generate footer unless the component is Footer.
- Do not generate hero section unless the component is Hero.
- If the component is Menu Section, generate restaurant food menu cards only.
- If the component is Reservation Form, generate only a booking/reservation form.
- Use the exact business/website name from Content Data if available.
- Do not add words like "Restaurant Named" before the brand name.
- Use the current year 2026 in footer copyright.
- Use Indian Rupee prices if prices are needed.
- Use semantic HTML tags.
- Use simple reusable class names.
- Do not include JavaScript.
- Do not include CSS.
"""

        try:
            return ask_gemini(prompt)
        except Exception as error:
            print("\nGemini failed or quota exceeded. Using local fallback UI.")
            print("Error:", error)

            return self.local_fallback(
                component_name=component_name,
                content_data=content_data,
                pages=pages,
                website_type=website_type
            )

    def local_fallback(self, component_name, content_data=None, pages=None, website_type="website"):
        if content_data is None:
            content_data = {}

        if pages is None:
            pages = ["Home", "Menu", "Reservation", "Contact"]

        name = content_data.get("name", "Sillyvibes")
        role = content_data.get("role", "Delicious Food, Fresh Ingredients, Unforgettable Taste")

        if component_name == "Navbar":
            links = ""
            for page in pages:
                links += f'<li><a href="#{page.lower()}">{page}</a></li>\n'

            return f"""
<nav class="navbar">
    <div class="navbar-container">
        <h2>{name}</h2>
        <ul>
            {links}
        </ul>
    </div>
</nav>
"""

        elif component_name == "Hero":
            return f"""
<section class="hero">
    <div class="hero-content">
        <h1>Welcome to {name}</h1>
        <p>{role}</p>
        <a href="#menu" class="btn">View Menu</a>
    </div>
</section>
"""

        elif component_name == "Menu Section":
            return """
<section class="menu-section" id="menu">
    <h2>Our Menu</h2>

    <div class="menu-grid">
        <div class="menu-card">
            <h3>Paneer Tikka</h3>
            <p>Spicy grilled paneer served with fresh mint chutney.</p>
            <span>₹249</span>
        </div>

        <div class="menu-card">
            <h3>Butter Naan & Curry</h3>
            <p>Fresh naan served with rich creamy curry.</p>
            <span>₹199</span>
        </div>

        <div class="menu-card">
            <h3>Veg Biryani</h3>
            <p>Flavourful rice cooked with vegetables and Indian spices.</p>
            <span>₹299</span>
        </div>

        <div class="menu-card">
            <h3>Chocolate Brownie</h3>
            <p>Warm brownie served with vanilla ice cream.</p>
            <span>₹149</span>
        </div>
    </div>
</section>
"""

        elif component_name == "Reservation Form":
            return """
<section class="reservation-section" id="reservation">
    <h2>Book a Table</h2>

    <form class="reservation-form">
        <input type="text" placeholder="Full Name" required>
        <input type="email" placeholder="Email Address" required>
        <input type="tel" placeholder="Phone Number" required>
        <input type="date" required>
        <input type="time" required>
        <input type="number" placeholder="Number of Guests" min="1" required>
        <textarea placeholder="Special Request"></textarea>
        <button type="submit">Confirm Reservation</button>
    </form>
</section>
"""

        elif component_name == "Footer":
            return f"""
<footer class="footer">
    <h3>{name}</h3>
    <p>{role}</p>
    <p>© 2026 {name}. All rights reserved.</p>
</footer>
"""

        elif component_name == "Projects Grid":
            return """
<section class="projects">
    <h2>Projects</h2>
    <div class="project-card">
        <h3>Sample Project</h3>
        <p>A beautiful project generated by the multiagent system.</p>
    </div>
</section>
"""

        elif component_name == "Article Grid":
            return """
<section class="articles">
    <h2>Latest Articles</h2>
    <div class="article-card">
        <h3>How AI is Changing Web Development</h3>
        <p>A quick article about AI-powered website generation.</p>
    </div>
</section>
"""

        elif component_name == "Features":
            return """
<section class="features">
    <h2>Features</h2>
    <div class="feature-card">
        <h3>Fast</h3>
        <p>Generate websites quickly using AI agents.</p>
    </div>
</section>
"""

        elif component_name == "Pricing":
            return """
<section class="pricing">
    <h2>Pricing</h2>
    <div class="pricing-card">
        <h3>Starter</h3>
        <p>₹499/month</p>
    </div>
</section>
"""

        elif component_name == "Product Grid":
            return """
<section class="products">
    <h2>Products</h2>
    <div class="product-card">
        <h3>Sample Product</h3>
        <p>₹999</p>
        <button>Add to Cart</button>
    </div>
</section>
"""

        elif component_name == "Cart":
            return """
<section class="cart">
    <h2>Your Cart</h2>
    <p>Your selected products will appear here.</p>
    <button>Checkout</button>
</section>
"""

        elif component_name == "Checkout":
            return """
<section class="checkout">
    <h2>Checkout</h2>
    <p>Enter your delivery and payment details.</p>
    <button>Place Order</button>
</section>
"""

        return ""